apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - command:
            - /home/prowler/docker-entrypoint.sh
            - prod
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: API_BASE_URL
                  name: env
            - name: AUTH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SECRET
                  name: env
            - name: AUTH_TRUST_HOST
              valueFrom:
                configMapKeyRef:
                  key: AUTH_TRUST_HOST
                  name: env
            - name: DJANGO_ACCESS_TOKEN_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCESS_TOKEN_LIFETIME
                  name: env
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: env
            - name: DJANGO_BIND_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_BIND_ADDRESS
                  name: env
            - name: DJANGO_CACHE_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_CACHE_MAX_AGE
                  name: env
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_DEBUG
                  name: env
            - name: DJANGO_LOGGING_FORMATTER
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_LOGGING_FORMATTER
                  name: env
            - name: DJANGO_LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_LOGGING_LEVEL
                  name: env
            - name: DJANGO_MANAGE_DB_PARTITIONS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_MANAGE_DB_PARTITIONS
                  name: env
            - name: DJANGO_PORT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_PORT
                  name: env
            - name: DJANGO_REFRESH_TOKEN_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_REFRESH_TOKEN_LIFETIME
                  name: env
            - name: DJANGO_SECRETS_ENCRYPTION_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRETS_ENCRYPTION_KEY
                  name: env
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: env
            - name: DJANGO_STALE_WHILE_REVALIDATE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_STALE_WHILE_REVALIDATE
                  name: env
            - name: DJANGO_TOKEN_SIGNING_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_TOKEN_SIGNING_KEY
                  name: env
            - name: DJANGO_TOKEN_VERIFYING_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_TOKEN_VERIFYING_KEY
                  name: env
            - name: DJANGO_WORKERS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_WORKERS
                  name: env
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_ADMIN_PASSWORD
                  name: env
            - name: POSTGRES_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_ADMIN_USER
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: PROWLER_API_VERSION
              valueFrom:
                configMapKeyRef:
                  key: PROWLER_API_VERSION
                  name: env
            - name: PROWLER_UI_VERSION
              valueFrom:
                configMapKeyRef:
                  key: PROWLER_UI_VERSION
                  name: env
            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                  key: SITE_URL
                  name: env
            - name: UI_PORT
              valueFrom:
                configMapKeyRef:
                  key: UI_PORT
                  name: env
            - name: VALKEY_DB
              valueFrom:
                configMapKeyRef:
                  key: VALKEY_DB
                  name: env
            - name: VALKEY_HOST
              valueFrom:
                configMapKeyRef:
                  key: VALKEY_HOST
                  name: env
            - name: VALKEY_PORT
              valueFrom:
                configMapKeyRef:
                  key: VALKEY_PORT
                  name: env
          image: prowlercloud/prowler-api:latest
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
      hostname: prowler-api
      restartPolicy: Always
