apiVersion: v1
binaryData:
  dump.rdb: VWtWRVNWTXdNREV4K2dwMllXeHJaWGt0ZG1WeUJUY3VNaTQxK2dweVpXUnBjeTFpYVhSendFRDZCV04wYVcxbHdnUElZbWY2Q0hWelpXUXRiV1Z0d3JBNEZnRDZDR0Z2WmkxaVlYTmx3QUQrQVBzRUFCUWNYMnR2YldKMUxtSnBibVJwYm1jdVkyVnNaWEo1TG5CcFpHSnZlQzR1QUFBQUFRQ2xCaFlHRm1ObGJHVnllVUJoWkdRNE5EQTFPREJpWVRNdVkyVnNaWEo1TG5CcFpHSnZlQ2IvRkJWZmEyOXRZblV1WW1sdVpHbHVaeTVqWld4bGNua1pHUUFBQUFFQWtHTmxiR1Z5ZVFZV0JoWmpaV3hsY25rUi94UVVYMnR2YldKMUxtSnBibVJwYm1jdWMyTmhibk1YRndBQUFBRUFqbk5qWVc1ekJoWUdGbk5qWVc1ekQvOFVGMTlyYjIxaWRTNWlhVzVrYVc1bkxtTmxiR1Z5ZVdWMncwQnZRSDBmZlFBQUFBSUF1WGR2Y210bGNpNGpCaFlHRm1ObGJHVnllV1YyTG1VeVltSWZNbVE1Tmkwd09ETmpMVFJsTlRRdE9XUXhOUzFrTmpVd09XUXlPR0ZrTnprQU91QU5PaDlpTURFM01XVTJaaTFqTnpObExUUmtZakV0WVdWaVl5MDJNVGMxWVRBMk5nVTRZamhoT3YvL1h1bmVydVBwOGJrPQ==
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: valkey
  name: valkey-cm0
